package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/drewdrewthis/supergraph/core"
)

// Health is the resolver for the health field. It delegates to the injected func
// so the graph package stays free of business logic.
func (r *queryResolver) Health(ctx context.Context) ([]core.HealthStatus, error) {
	if r.Resolver.Health == nil {
		return nil, nil
	}
	return r.Resolver.Health(ctx), nil
}

// Ping is the resolver for the ping field: a liveness token that keeps the root
// Query type non-empty before any plugin extends it.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "ok", nil
}

// PluginLag is the resolver for the pluginLag field. It delegates to the injected
// stream func; a nil func yields a closed channel (no pushes) rather than a panic.
func (r *subscriptionResolver) PluginLag(ctx context.Context, thresholdSeconds float64) (<-chan core.HealthStatus, error) {
	if r.Resolver.Lag == nil {
		ch := make(chan core.HealthStatus)
		close(ch)
		return ch, nil
	}
	return r.Resolver.Lag(ctx, thresholdSeconds), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
