package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/drewdrewthis/supergraph/graph/model"
	"github.com/drewdrewthis/supergraph/plugins/claude"
)

// ClaudeSessions is the resolver for the claudeSessions field. It delegates to the
// claude plugin through its package funcs (the running instance is published in
// Migrate), so graph/ carries no plugin logic — the S5 zero-core-edit seam.
func (r *queryResolver) ClaudeSessions(ctx context.Context, hostID *string, issueNumber *int) ([]model.ClaudeSession, error) {
	rows := claude.QuerySessions(ctx, hostID, issueNumber)
	out := make([]model.ClaudeSession, 0, len(rows))
	for _, row := range rows {
		out = append(out, claudeSessionModel(row))
	}
	return out, nil
}

// ClaudeSession is the resolver for the claudeSession field.
func (r *queryResolver) ClaudeSession(ctx context.Context, sessionID string) (*model.ClaudeSession, error) {
	row := claude.QuerySession(ctx, sessionID)
	if row == nil {
		return nil, nil
	}
	m := claudeSessionModel(*row)
	return &m, nil
}

// ClaudeInstances is the resolver for the claudeInstances field.
func (r *queryResolver) ClaudeInstances(ctx context.Context, hostID *string) ([]model.ClaudeInstance, error) {
	rows := claude.QueryInstances(ctx, hostID)
	out := make([]model.ClaudeInstance, 0, len(rows))
	for _, row := range rows {
		s := claudeSessionModel(row)
		out = append(out, model.ClaudeInstance{HostID: row.HostID, Pane: row.Pane, Pid: row.Pid, Session: &s, StaleSince: row.StaleSince})
	}
	return out, nil
}

// ClaudeSessionUpdated is the resolver for the claudeSessionUpdated field. Like the
// template plugin's, it maps envelopes from the injected Events hook into the model,
// keeping graph/ free of per-plugin logic. The raw envelope shape lets consumers
// verify the payload carries only metadata (AC-CLAUDE-PRIVACY).
func (r *subscriptionResolver) ClaudeSessionUpdated(ctx context.Context, hostID *string) (<-chan model.ClaudeEvent, error) {
	out := make(chan model.ClaudeEvent)
	if r.Resolver.Events == nil {
		close(out)
		return out, nil
	}
	in := r.Resolver.Events(ctx, "claude")
	go func() {
		defer close(out)
		for e := range in {
			select {
			case out <- model.ClaudeEvent{Ts: e.TS, Type: e.Type, V: e.V, Key: e.Key, Payload: string(e.Payload)}:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}
