package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	"github.com/drewdrewthis/supergraph/graph/model"
	"github.com/drewdrewthis/supergraph/internal/issuekey"
	"github.com/drewdrewthis/supergraph/plugins/git"
	"github.com/drewdrewthis/supergraph/plugins/github"
	"github.com/drewdrewthis/supergraph/plugins/tmux"
)

// Repos is the resolver for the repos field: cache-only, [] when the plugin has
// nothing cached for hostID (nil hostID means all hosts).
func (r *queryResolver) Repos(ctx context.Context, hostID *string) ([]git.RepoNode, error) {
	id := ""
	if hostID != nil {
		id = *hostID
	}
	rows := git.Repos(ctx, id)
	out := make([]git.RepoNode, 0, len(rows))
	out = append(out, rows...)
	return out, nil
}

// Worktrees is the resolver for the worktrees field: cache-only, [] when the repo
// has no cached worktrees.
func (r *repoResolver) Worktrees(ctx context.Context, obj *git.RepoNode) ([]git.WorktreeNode, error) {
	rows := git.WorktreesForRepo(ctx, obj.Key)
	out := make([]git.WorktreeNode, 0, len(rows))
	out = append(out, rows...)
	return out, nil
}

// WorktreeUpdated is the resolver for the worktreeUpdated field. Like the github
// plugin's CheckRunUpdated it carries no business logic: it maps envelopes from the
// injected Events hook (filtered server-side to Source "git" by core at
// server-build time) into the GraphQL model, keeping graph/ free of per-plugin
// logic per the S5 seam.
func (r *subscriptionResolver) WorktreeUpdated(ctx context.Context) (<-chan model.GitEvent, error) {
	out := make(chan model.GitEvent)
	if r.Resolver.Events == nil {
		close(out)
		return out, nil
	}

	in := r.Resolver.Events(ctx, "git")
	go func() {
		defer close(out)
		for e := range in {
			select {
			case out <- model.GitEvent{
				Ts:      e.TS,
				Type:    e.Type,
				V:       e.V,
				Key:     e.Key,
				Payload: string(e.Payload),
			}:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}

// TmuxSession is the resolver for the tmuxSession field (AC-GIT-TMUX-JOIN): the
// tmux session parked on obj's worktree path. See tmuxSessionForWorktree in
// graph/git_map.go for the match/tie-break rule and the symlink-out-of-scope note.
func (r *worktreeResolver) TmuxSession(ctx context.Context, obj *git.WorktreeNode) (*model.TmuxSession, error) {
	sessions, err := tmux.Sessions(ctx, "")
	if err != nil {
		return nil, nil
	}
	return tmuxSessionForWorktree(sessions, obj.Path), nil
}

// Issue is the resolver for the issue field: the cached issue the worktree's
// branch derives to via the shared issuekey join, scoped by obj.RepoSlug. A cold
// cache, an unparseable branch, or a malformed RepoSlug all legitimately yield nil.
func (r *worktreeResolver) Issue(ctx context.Context, obj *git.WorktreeNode) (*github.IssueNode, error) {
	if obj.Branch == nil {
		return nil, nil
	}
	branch := *obj.Branch
	n, ok := issuekey.FromBranch(branch)
	if !ok {
		return nil, nil
	}
	owner, repo, ok := splitRepoSlug(obj.RepoSlug)
	if !ok {
		return nil, nil
	}
	return github.Issue(ctx, fmt.Sprintf("issue:%s/%s#%d", owner, repo, n)), nil
}

// PullRequest is the resolver for the pullRequest field (AC-GIT-PR-JOIN). See
// pullRequestForWorktree in graph/git_map.go for the two-path join (issue-key cache
// hit checked against HeadRefName, then a fallback scan of cached PRs) — state is
// never filtered, so a closed/merged PR on the branch is still returned.
func (r *worktreeResolver) PullRequest(ctx context.Context, obj *git.WorktreeNode) (*github.PRNode, error) {
	if obj.Branch == nil {
		return nil, nil
	}
	branch := *obj.Branch
	owner, repo, ok := splitRepoSlug(obj.RepoSlug)
	if !ok {
		return nil, nil
	}
	var direct *github.PRNode
	if n, ok := issuekey.FromBranch(branch); ok {
		direct = github.PullRequest(ctx, fmt.Sprintf("pr:%s/%s#%d", owner, repo, n))
	}
	cached := github.CachedPRs(ctx, owner, repo)
	return pullRequestForWorktree(direct, cached, branch), nil
}

// Repo returns RepoResolver implementation.
func (r *Resolver) Repo() RepoResolver { return &repoResolver{r} }

// Worktree returns WorktreeResolver implementation.
func (r *Resolver) Worktree() WorktreeResolver { return &worktreeResolver{r} }

type (
	repoResolver     struct{ *Resolver }
	worktreeResolver struct{ *Resolver }
)
