package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"strings"

	"github.com/drewdrewthis/supergraph/graph/model"
	"github.com/drewdrewthis/supergraph/plugins/github"
)

// TmuxPanes resolves the panes joined to this issue (the join lives in graph/, D2).
func (r *issueResolver) TmuxPanes(ctx context.Context, obj *github.IssueNode) ([]model.TmuxPane, error) {
	return tmuxPanesForIssue(ctx, obj), nil
}

// ClaudeSessions resolves the claude sessions joined to this issue.
func (r *issueResolver) ClaudeSessions(ctx context.Context, obj *github.IssueNode) ([]model.ClaudeSession, error) {
	return claudeSessionsForIssue(ctx, obj), nil
}

// TmuxPanes resolves the panes on this PR's head branch (D3).
func (r *pullRequestResolver) TmuxPanes(ctx context.Context, obj *github.PRNode) ([]model.TmuxPane, error) {
	return panesForBranchModel(ctx, obj.HeadRefName), nil
}

// ClaudeSessions resolves the claude sessions on this PR's head branch (D3).
func (r *pullRequestResolver) ClaudeSessions(ctx context.Context, obj *github.PRNode) ([]model.ClaudeSession, error) {
	return claudeSessionsOnBranchModel(ctx, obj.HeadRefName), nil
}

// Issue is the resolver for the issue field: cache-only, null on a miss (D1).
func (r *queryResolver) Issue(ctx context.Context, key string) (*github.IssueNode, error) {
	return github.Issue(ctx, key), nil
}

// PullRequest is the resolver for the pullRequest field: cache-only, null on a miss.
func (r *queryResolver) PullRequest(ctx context.Context, key string) (*github.PRNode, error) {
	return github.PullRequest(ctx, key), nil
}

// IssuesForRepo is the resolver for the issuesForRepo field: cache-only, [] cold.
func (r *queryResolver) IssuesForRepo(ctx context.Context, owner string, repo string) ([]github.IssueNode, error) {
	return github.IssuesForRepo(ctx, owner, repo), nil
}

// CheckRunUpdated is the resolver for the checkRunUpdated field. Like the template
// plugin's subscription it carries no business logic: it maps envelopes from the
// injected Events hook (filtered server-side to Source "github" by core at
// server-build time) into the GraphQL model, keeping graph/ free of per-plugin
// logic per the S5 seam. Every github webhook purge/update emits one such
// envelope, so S3 sees a push per receipt.
func (r *subscriptionResolver) CheckRunUpdated(ctx context.Context) (<-chan model.GithubEvent, error) {
	out := make(chan model.GithubEvent)
	if r.Resolver.Events == nil {
		close(out)
		return out, nil
	}

	in := r.Resolver.Events(ctx, "github")
	go func() {
		defer close(out)
		for e := range in {
			select {
			case out <- model.GithubEvent{
				Ts:      e.TS,
				Type:    e.Type,
				V:       e.V,
				Key:     e.Key,
				Payload: string(e.Payload),
			}:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}

// IssueUpdated is the resolver for the issueUpdated field. Same mechanics as
// CheckRunUpdated (S5 seam, no per-plugin logic in graph/): it relays github
// envelopes from the injected Events hook, keeping only issue-kind keys
// (`issue:{owner}/{repo}#N`, so a check_run or purge of another kind never fires an
// issueUpdated push). The optional owner/repo args narrow the relay by the key's
// `issue:owner/repo#` prefix, mirroring claudeSessionUpdated's hostId suffix filter.
func (r *subscriptionResolver) IssueUpdated(ctx context.Context, owner *string, repo *string) (<-chan model.GithubEvent, error) {
	if repo != nil && owner == nil {
		return nil, fmt.Errorf("issueUpdated: repo requires owner")
	}
	out := make(chan model.GithubEvent)
	if r.Resolver.Events == nil {
		close(out)
		return out, nil
	}
	prefix := "issue:"
	if owner != nil {
		prefix += *owner + "/"
		if repo != nil {
			prefix += *repo + "#"
		}
	}
	in := r.Resolver.Events(ctx, "github")
	go func() {
		defer close(out)
		for e := range in {
			if !strings.HasPrefix(e.Key, prefix) {
				continue
			}
			select {
			case out <- model.GithubEvent{Ts: e.TS, Type: e.Type, V: e.V, Key: e.Key, Payload: string(e.Payload)}:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}

// Issue returns IssueResolver implementation.
func (r *Resolver) Issue() IssueResolver { return &issueResolver{r} }

// PullRequest returns PullRequestResolver implementation.
func (r *Resolver) PullRequest() PullRequestResolver { return &pullRequestResolver{r} }

type (
	issueResolver       struct{ *Resolver }
	pullRequestResolver struct{ *Resolver }
)
