package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/drewdrewthis/supergraph/graph/model"
)

// CheckRunUpdated is the resolver for the checkRunUpdated field. Like the template
// plugin's subscription it carries no business logic: it maps envelopes from the
// injected Events hook (filtered server-side to Source "github" by core at
// server-build time) into the GraphQL model, keeping graph/ free of per-plugin
// logic per the S5 seam. Every github webhook purge/update emits one such
// envelope, so S3 sees a push per receipt.
func (r *subscriptionResolver) CheckRunUpdated(ctx context.Context) (<-chan model.GithubEvent, error) {
	out := make(chan model.GithubEvent)
	if r.Resolver.Events == nil {
		close(out)
		return out, nil
	}

	in := r.Resolver.Events(ctx, "github")
	go func() {
		defer close(out)
		for e := range in {
			select {
			case out <- model.GithubEvent{
				Ts:      e.TS,
				Type:    e.Type,
				V:       e.V,
				Key:     e.Key,
				Payload: string(e.Payload),
			}:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}
