package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/drewdrewthis/supergraph/graph/model"
	"github.com/drewdrewthis/supergraph/plugins/peer"
)

// Peers is the resolver for the peers field. It carries no business logic: it
// delegates to the peer plugin's own liveness accessor and maps the view onto the
// GraphQL model, keeping graph/ free of per-plugin logic (S5 seam). The plugin
// publishes the accessor as a package singleton, so graph never edits core/server.
func (r *queryResolver) Peers(ctx context.Context) ([]model.Peer, error) {
	views, err := peer.Peers(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]model.Peer, 0, len(views))
	for _, v := range views {
		out = append(out, model.Peer{
			HostID:                    v.HostID,
			URL:                       v.URL,
			LastSeenAt:                v.LastSeenAt,
			StaleSince:                v.StaleSince,
			RemoteMaxPluginLagSeconds: v.LagSeconds,
			MirroredKeys:              v.MirroredKeys,
		})
	}
	return out, nil
}
