package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/drewdrewthis/supergraph/graph/model"
)

// TemplatePing is the resolver for the templatePing field.
func (r *queryResolver) TemplatePing(ctx context.Context) (string, error) {
	return "pong from template", nil
}

// TemplateEvents is the resolver for the templateEvents field. It carries no
// business logic itself: it maps envelopes from the injected Events hook (owned
// by core at server-build time) into the GraphQL model, keeping graph/ free of
// per-plugin logic per the S5 seam.
func (r *subscriptionResolver) TemplateEvents(ctx context.Context) (<-chan model.TemplateEvent, error) {
	out := make(chan model.TemplateEvent)
	if r.Resolver.Events == nil {
		close(out)
		return out, nil
	}

	in := r.Resolver.Events(ctx, "template")
	go func() {
		defer close(out)
		for e := range in {
			select {
			case out <- model.TemplateEvent{
				Ts:      e.TS,
				Type:    e.Type,
				V:       e.V,
				Key:     e.Key,
				Payload: string(e.Payload),
			}:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}
