package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/drewdrewthis/supergraph/graph/model"
	"github.com/drewdrewthis/supergraph/plugins/tmux"
)

// TmuxSessions is the resolver for the tmuxSessions field. It delegates to the
// running tmux plugin (the S5 seam: graph reaches the live store without a core
// edit) and maps rows to the generated model. Helpers live in tmux_helpers.go so
// gqlgen's follow-schema regen (which only preserves resolver method bodies) never
// strips them.
func (r *queryResolver) TmuxSessions(ctx context.Context, hostID *string) ([]model.TmuxSession, error) {
	rows, err := tmux.Sessions(ctx, hostArg(hostID))
	if err != nil {
		return nil, err
	}
	bySession, err := tmux.WindowsBySession(ctx, hostArg(hostID))
	if err != nil {
		return nil, err
	}
	out := make([]model.TmuxSession, 0, len(rows))
	for _, s := range rows {
		out = append(out, sessionToModel(s, bySession[s.Name]))
	}
	return out, nil
}

// TmuxPanes is the resolver for the tmuxPanes field.
func (r *queryResolver) TmuxPanes(ctx context.Context, hostID *string) ([]model.TmuxPane, error) {
	rows, err := tmux.Panes(ctx, hostArg(hostID))
	if err != nil {
		return nil, err
	}
	return panesToModel(rows), nil
}

// Slots is the resolver for the slots field.
func (r *queryResolver) Slots(ctx context.Context, hostID *string) ([]model.Slot, error) {
	return slotsModel(ctx, hostArg(hostID), false)
}

// FreeSlots is the resolver for the freeSlots field.
func (r *queryResolver) FreeSlots(ctx context.Context, hostID *string) ([]model.Slot, error) {
	return slotsModel(ctx, hostArg(hostID), true)
}

// PaneForBranch is the resolver for the paneForBranch field.
func (r *queryResolver) PaneForBranch(ctx context.Context, branch string) ([]model.TmuxPane, error) {
	rows, err := tmux.PaneForBranch(ctx, branch)
	if err != nil {
		return nil, err
	}
	return panesToModel(rows), nil
}

// TmuxEvents is the resolver for the tmuxEvents field. Like templateEvents it maps
// the plugin's own envelopes (Source "tmux") from the injected Events hook into the
// GraphQL model, keeping graph/ free of per-plugin business logic (S5 seam).
func (r *subscriptionResolver) TmuxEvents(ctx context.Context) (<-chan model.TmuxEvent, error) {
	out := make(chan model.TmuxEvent)
	if r.Resolver.Events == nil {
		close(out)
		return out, nil
	}
	in := r.Resolver.Events(ctx, "tmux")
	go func() {
		defer close(out)
		for e := range in {
			select {
			case out <- model.TmuxEvent{Ts: e.TS, Type: e.Type, V: e.V, Key: e.Key, Payload: string(e.Payload)}:
			case <-ctx.Done():
				return
			}
		}
	}()
	return out, nil
}
