// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type ClaudeEvent struct {
	Ts      time.Time `json:"ts"`
	Type    string    `json:"type"`
	V       int       `json:"v"`
	Key     string    `json:"key"`
	Payload string    `json:"payload"`
}

type ClaudeInstance struct {
	HostID     string         `json:"hostId"`
	Pane       string         `json:"pane"`
	Pid        int            `json:"pid"`
	Session    *ClaudeSession `json:"session"`
	StaleSince *time.Time     `json:"staleSince,omitempty"`
}

type ClaudeSession struct {
	HostID      string     `json:"hostId"`
	SessionID   string     `json:"sessionId"`
	Cwd         string     `json:"cwd"`
	GitBranch   *string    `json:"gitBranch,omitempty"`
	IssueNumber *int       `json:"issueNumber,omitempty"`
	Model       *string    `json:"model,omitempty"`
	State       string     `json:"state"`
	LastTool    *string    `json:"lastTool,omitempty"`
	ToolCalls   int        `json:"toolCalls"`
	PrNumber    *int       `json:"prNumber,omitempty"`
	PrURL       *string    `json:"prUrl,omitempty"`
	StartedAt   time.Time  `json:"startedAt"`
	LastEventAt time.Time  `json:"lastEventAt"`
	StaleSince  *time.Time `json:"staleSince,omitempty"`
}

type GithubEvent struct {
	Ts      time.Time `json:"ts"`
	Type    string    `json:"type"`
	V       int       `json:"v"`
	Key     string    `json:"key"`
	Payload string    `json:"payload"`
}

type Peer struct {
	HostID     string     `json:"hostId"`
	URL        string     `json:"url"`
	LastSeenAt *time.Time `json:"lastSeenAt,omitempty"`
	StaleSince *time.Time `json:"staleSince,omitempty"`
	// The remote's own worst plugin lag (seconds), mirrored from its pluginLag stream —
	// NOT the health of this peer link. A remote plugin stuck "starting" reports a large
	// value here while staleSince stays null (the link itself is up). staleSince, driven
	// by a WS drop / 401, is the signal for "this peer is unreachable".
	RemoteMaxPluginLagSeconds float64 `json:"remoteMaxPluginLagSeconds"`
	MirroredKeys              int     `json:"mirroredKeys"`
}

type Query struct {
}

type Subscription struct {
}

type TemplateEvent struct {
	Ts      time.Time `json:"ts"`
	Type    string    `json:"type"`
	V       int       `json:"v"`
	Key     string    `json:"key"`
	Payload string    `json:"payload"`
}
